spring:
  application:
    name: spr202602
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    #hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.jdbc.time_zone: Asia/Seoul
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    remote:
      restart:
        enabled: false
  freemarker:
    cache: false
  sql.init.mode: always
  #sql.init.mode: never

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3306/scspr202602?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver